---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "gmazoyer"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "gmazoyer"
  - package-ecosystem: "docker-compose"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    assignees:
      - "gmazoyer"
